### ISSUE TITLE
CourseKey.from_string cannot find deprecated_fallback

### ISSUE THREAD

**Issue by clintonb** [edx/opaque-keys#41]
I am seeing a strange issue with `CourseKey.from_string`. When I pass `u'edX/DemoX/Demo_Course'` as an argument in tests, no error is raised. When I pass the same argument while processing a Django request and InvalidKeyError is raised. This issue is present after commit d45d0bd8d64c69531be69178b9505b5d38806ce0.

**Comment by cpennington** [comment]
I think we've nailed this down, so I'm going to close it.
